### ISSUE TITLE
TypeError: '<' not supported between instances of 'Facet3D' and 'Facet3D'

### ISSUE THREAD

**Issue by salfter** [revarbat/stl_normalize#1]
I'm getting this error when I try to normalize a file:

```
Traceback (most recent call last):
  File "/usr/bin/stl_normalize", line 1276, in <module>
    main()
  File "/usr/bin/stl_normalize", line 1265, in main
    stl.write_file(args.outfile, binary=args.write_binary)
  File "/usr/bin/stl_normalize", line 784, in write_file
    self._write_ascii_file(filename)
  File "/usr/bin/stl_normalize", line 748, in _write_ascii_file
    for facet in self.facets.sorted():
  File "/usr/bin/stl_normalize", line 605, in sorted
    for pt in sorted(vals):
TypeError: '<' not supported between instances of 'Facet3D' and 'Facet3D'
```

I'm using Python 3.8 on Gentoo Linux, if it matters.

**Comment by lenaschimmel** [comment]
This is probably caused Python 3 no longer supports using ``__cmp__`` to override comparison operators. Instead, ``__lt__`` must be used for the `<` operator.

A similar problem occurs with `__div__`, which has been replaced by ``__truediv__`` in Python 3.
